# Generated by Django 4.0 on 2021-12-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=50)),
                ('filesize', models.IntegerField()),
                ('fileupl', models.FileField(upload_to='files/')),
            ],
        ),
    ]
